[package]
name = "framework-power-measurment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.6"
plotters = "0.3.3"
crossterm = "0.23"
rand = "*"
serde = "*"
anyhow = "*"
